---
name: docker

on:
  push:
    branches: [main]
    paths: ['Dockerfile', 'src/prefect_shared_tasks/**.py', 'scripts/**', 'poetry.lock', 'pyproject.toml']
  pull_request:
    paths: ['Dockerfile', 'src/prefect_shared_tasks/**.py', 'scripts/**', 'poetry.lock', 'pyproject.toml']

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gmontanola/custom-prefect:latest
          cache-from: type=gha,scope=build
          cache-to: type=gha,mode=max,scope=build
