---
name: prefect-register

on:
  push:
    branches: [main]
    paths: ['flows/**.py']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            flows\/.*\.py

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Prefect
        run: python -m pip install prefect

      - name: Login to Prefect
        run: prefect auth login -t ${{secrets.PREFECT_TOKEN}}

      - name: Register flow(s)
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            prefect register --project prefect-k8s-poc --path "$file"
          done
